### ISSUE TITLE
Segfault in binary_search()

### ISSUE THREAD

**Issue by kylelutz** [boostorg/compute#271]
I was looking at the coverage report for the `detail::binary_find()` algorithm (https://coveralls.io/files/301660135) at tried writing a test which used the `binary_find_kernel` (by making the input range larger than 128 values) but got a segfault when running:

```
Running 3 test cases...
Segmentation fault (core dumped)
```

Here's the test case:
```
BOOST_AUTO_TEST_CASE(binary_search_large)
{
    compute::vector<int> vec(1000, context);
    compute::iota(vec.begin(), vec.end(), 1, queue);

    BOOST_CHECK(compute::binary_search(vec.begin(), vec.end(), int(0)) == false);
    BOOST_CHECK(compute::binary_search(vec.begin(), vec.end(), int(1)) == true);
    BOOST_CHECK(compute::binary_search(vec.begin(), vec.end(), int(1000)) == true);
    BOOST_CHECK(compute::binary_search(vec.begin(), vec.end(), int(1001)) == false);
}
```

@roshanr95 can you reproduce this? Any ideas?

**Comment by haahh** [comment]
Currently in [test_binary_search.cpp](https://github.com/boostorg/compute/blob/master/test/test_binary_search.cpp) there is a test with a large input and the problem is gone for some time (there were some changes introduced to [binary_find.hpp](https://github.com/boostorg/compute/blob/master/include/boost/compute/algorithm/detail/binary_find.hpp) and maybe they fixed this problem). IMHO, this can be closed.
