### ISSUE TITLE
Reduce, transform_reduce of multiple intervals

### ISSUE THREAD

**Issue by dPavelDev** [boostorg/compute#685]
It is possible to efficiently reduce or transform_reduce of multiple intervals in array? Distances between begin and end of iterators in interval may be different, intervals hasn't intersections.

**Comment by haahh** [comment]
I think that currently the best option is to perform a scan and pick values
that you want from the result. However, you'll have to benchmark if it's
faster than performing multiple reduce operations. Otherwise, you'll have
to modify reduce algorithm.

14 sty 2017 18:01 "Pavel Darashkevich" <notifications@github.com>
napisał(a):
