### ISSUE TITLE
lru_cache does not allow to update current value in the cache

### ISSUE THREAD

**Issue by vertexodessa** [boostorg/compute#749]
https://github.com/boostorg/compute/blob/master/include/boost/compute/detail/lru_cache.hpp#L66
"insert" function silently returns if the cache already contains the key, without updating the current value.

There is also no API to remove the value if the cache contains an item associated with the key, so it looks like it's hard to work around this limitation.

**Comment by Ulfgard** [comment]
a workaround for this limitation is to use get after insertion as this will update the list. This costs an additional map lookup, but should be fine performance-wise.

**Comment by vertexodessa** [comment]
using get will not update the value of the key
cache.insert(1,1);
cache.insert(1,2);
cache.get(1);  // what would you expect this to return?

**Comment by jszuppe** [comment]
This class was designed for storing compiled OpenCL programs (kernels). That's why there's no need to update value on `insert()`. It assumes that (key, values) pairs are unique, which means you can't have pairs (1,1) and (1,2). Also, it's in `detail::` namespace, which means it's not a public API. 

I'm closing the issue, marking not-a-bug. Please reopen if this behaviour causes problems in Boost.Compute, for example: bad program is run.
