### ISSUE TITLE
Support setting kernel argument as NULL

### ISSUE THREAD

**Issue by rosenrodt** [boostorg/compute#828]
As per Khronos OpenCL spec:
> If the argument is declared to be a pointer of a built-in scalar or vector type, or a user defined structure type in the global or constant address space, the memory object specified as argument value must be a buffer object **(or NULL)**.

I tried to set kernel argument like this 
```c++
some_kernel.set_arg(0, NULL);
```
but get error `invalid argument size` instead.

Because OpenCL explicitly allows NULL as input, I went on to see why and now maybe I've identified the problem:

```c++
// set_kernel_arg implementation for built-in types (including NULL)
template<class T>
struct set_kernel_arg
{
    typename boost::enable_if<is_fundamental<T> >::type
    operator()(kernel &kernel_, size_t index, const T &value)
    {
        kernel_.set_arg(index, sizeof(T), &value);
//                                        ^^^^^^
//                     now we are getting the address of NULL 
//                     certainly CL API won't allow an arbitrary address
    }
};
```
So Boost Compute needs somehow to identify the NULL, maybe via a special type inside `boost::compute`, and set the value NULL directly to the CL API instead of its address.

**Comment by jszuppe** [comment]
I don't think it's a valid option. I can undestand why someone would like to pass a null pointer when the argument isn't requied or won't be used in OpenCL C API, but in Boost.Compute's API you would have to pass an uninitialized buffer object.

Also I don't see good solution to support that (using `NULL` is ` void set_arg(size_t index, const T &value)`, because `NULL` does not have its own type. 

User can always use `void set_arg(size_t index, size_t size, const void *value)` which will work correctly with `NULL`. Another way would be to specify the type

**Comment by rosenrodt** [comment]
> User can always use void set_arg(size_t index, size_t size, const void *value) which will work correctly with NULL.

I wasn't aware of that. That should solve my issue, but felt using something like `std::nullptr_t` or `compute::null_t` would be neater. This way it also plays nice with the variadic `set_args(T&&... args)`

**Comment by jszuppe** [comment]
We can add overload for `std::nullptr_t`, which will fix it for C++11 and newer, so it should have in variadic version.
